### PR TITLE
Add API and address config to enable testing bootz service in tests

### PR DESCRIPTION
**Pull request by LiamWalsh98**
This revisits changes from #28 (rebased onto 6401680)

I will add the remaining changes to this draft PR and promote it for merging when finished.

### CODE REVIEW

**Comment by melzhan** [comment]
Your CL is failing some tests, please take a look here: https://github.com/openconfig/bootz/actions/runs/6435283126/job/17476203671?pr=64

**Comment by LiamWalsh98** [comment]
build is failing after presumably from a cherry-pick going wrong. will investigate

**Comment by LiamWalsh98** [comment]
squashed together several check fixes to reduce clutter

**Comment by melzhan** [comment]
Hey Liam, unclear if this is awaiting review, if it is, please set the PR as "Ready for review" Thanks :)

**Comment by LiamWalsh98** [comment]
> Hey Liam, unclear if this is awaiting review, if it is, please set the PR as "Ready for review" Thanks :)

Not quite yet, will mark as ready soon.

**Comment by LiamWalsh98** [comment]
redundant after #101

**Pull request closed without merging**
